#!/usr/bin/env bash
# Refresh the Xcode project's bundled web extension from the latest WXT build,
# WITHOUT re-running the converter (preserves signing / Info.plist / pbxproj hand edits).
# Auto-detects the extension target's Resources dir(s) regardless of converter layout.
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$REPO_ROOT/extension/.output/safari-mv3"
[ -d "$SRC" ] || { echo "Build first: scripts/build-safari.sh"; exit 1; }
# Scope to the source project only (apple/OpenTranslate), NOT apple/DerivedData
# build products — those are regenerated by xcodebuild from the source.
RES_DIRS="$(/usr/bin/find "$REPO_ROOT/apple/OpenTranslate" -type d -path '*Extension*/Resources' 2>/dev/null || true)"
if [ -z "$RES_DIRS" ]; then
  echo "No '*Extension*/Resources' dir found under apple/. Generate the project first: scripts/gen-xcode.sh"
  exit 1
fi
printf '%s\n' "$RES_DIRS" | while IFS= read -r d; do
  [ -n "$d" ] || continue
  echo "→ syncing $SRC → $d"
  rsync -a --delete "$SRC"/ "$d"/
done
echo "✓ Synced. Rebuild in Xcode (or via xcodebuild) to pick up the new bundle."
